FROM ubuntu:18.10

ARG UNAME=user
ARG UID=1000
ARG GID=1000

RUN apt-get update
RUN apt-get -y install cmake g++
RUN apt-get -y install valgrind gdb strace
RUN apt-get -y install libhdf5-dev libeigen3-dev

RUN groupadd -g $GID -o $UNAME && useradd -m -u $UID -g $GID -o -s /bin/bash $UNAME

USER $UNAME
RUN mkdir /home/${UNAME}/kite
WORKDIR /home/${UNAME}/kite
